# Generated by Django 6.0.2 on 2026-03-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='MA32225190', max_length=10, unique=True),
        ),
    ]
