# Generated by Django 6.0.2 on 2026-03-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='MA81407329', max_length=10, unique=True),
        ),
    ]
