# Generated by Django 6.0.2 on 2026-03-06 15:35

import wallet.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=wallet.util.generate_reference_number, max_length=10),
        ),
    ]
